strictness: high
test-warnings: true
doc-warnings: true

ignore-paths:
  - docs

# ignore-patterns:
#   - (^|/)skip(this)?(/|$)

pycodestyle:
  disable:
    - W602
    - W603
  enable:
    - W601
  options:
    max-line-length: 99

pylint:
  options:
    django-settings-module: controller/settings.py