FROM python:3.7.2-alpine3.8

LABEL maintainer="morgan.jon@gmail.com"
LABEL version="1.0"

ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  PIPENV_HIDE_EMOJIS=true \
  PIPENV_COLORBLIND=true \
  PIPENV_NOSPIN=true

RUN apk --no-cache add \
    bash \
    build-base \
    curl \
    gcc \
    gettext \
    libffi-dev \
    linux-headers \
    musl-dev \
    openldap-dev \
    postgresql-dev \
    tini
#    openssl-dev \ it's libressl-dev on Apline, but it get picked up
#    git \

# Creating folders, and files for a project:
COPY . /app
WORKDIR /app

# Project initialization:
#   && pipenv install --deploy --system --ignore-pipfile \
RUN pip install pipenv \
   && pipenv install --deploy --system \
   && python manage.py makemigrations --noinput \
   && python manage.py migrate --noinput

# expose port 8000
EXPOSE 8000

# /usr/local/bin/gunicorn server.wsgi -w 4 -b 0.0.0.0:8000 --chdir=/code
# ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/gunicorn self_service.wsgi"]
# CMD ["/sbin/tini", "--", "/usr/local/bin/gunicorn self_service.wsgi"]
CMD ["/usr/local/bin/gunicorn", "--bind", "0.0.0.0:8000", "self_service.wsgi"]
