version: "3.3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    extra_hosts:
          - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: ../public
        target: /public