# Generated by Django 2.2.1 on 2019-05-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('bcm', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('gpio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ZoneSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dow', models.CharField(max_length=7)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('zone', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
