# Generated by Django 4.1.1 on 2022-09-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zonemap",
            name="num",
            field=models.IntegerField(unique=True),
        ),
    ]
